version: '3'
services:
  mysql-development:
    platform: linux/x86_64
    container_name: mysql-development
    image: 'mysql:5.7.10'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'development'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
